[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
spl = "39spdgoF9pMG7BRAA2Gnp6fPi8zNGZUBtq73kuNsonh7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/spl"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/amm.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
