[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spl = "C1QrbSXfsm94jPzoucAa8ZX3EdxTUeDvJP9mV8NtZxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/spl"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
start       = false
ledger      = ".anchor/test-ledger"
bind_address= "0.0.0.0"
url         = "http://127.0.0.1:8899"